"use client";
import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useSession } from "next-auth/react";
type RequestRow={id:string;message:string;response:string|null;status:string;createdAt:string};
type Report={referenceNumber:string;address:string;description:string;status:string;infoRequests:RequestRow[]};
export default function ReporterCasePage({params}:{params:Promise<{id:string}>}){const{id}=use(params);const{status:sessionStatus}=useSession();const router=useRouter();const[report,setReport]=useState<Report|null>(null);const[answers,setAnswers]=useState<Record<string,string>>({});const[error,setError]=useState("");
 useEffect(()=>{if(sessionStatus==="unauthenticated")router.push("/login");if(sessionStatus==="authenticated")fetch(`/api/reports/${id}`).then(async r=>{if(!r.ok){setError("Report not found or access denied.");return;}setReport(await r.json());});},[id,sessionStatus,router]);
 async function reply(requestId:string){setError("");const r=await fetch(`/api/reports/${id}/info-request`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({infoRequestId:requestId,response:answers[requestId]})});const data=await r.json();if(!r.ok)return setError(data.error);setReport(x=>x?{...x,infoRequests:x.infoRequests.map(q=>q.id===requestId?data:q)}:x);setAnswers(x=>({...x,[requestId]:""}));}
 return <main className="max-w-3xl mx-auto p-6"><Link href="/dashboard" className="text-primary text-sm">← My reports</Link>{error&&<p role="alert" className="mt-4 text-red-600">{error}</p>}{report&&<><h1 className="text-2xl font-bold mt-4">{report.referenceNumber}</h1><p className="text-sm text-gray-600 mt-2">{report.status.replaceAll("_"," ")} · {report.address}</p><p className="mt-4 text-gray-700">{report.description}</p><h2 className="text-lg font-semibold mt-8 mb-3">Information requests</h2>{report.infoRequests.length===0&&<p className="text-sm text-gray-500">No information requests.</p>}<div className="space-y-4">{report.infoRequests.map(q=><section key={q.id} className="border rounded-xl bg-white p-4"><p className="font-medium">{q.message}</p><p className="text-xs text-gray-500 mt-1">{q.status} · {new Date(q.createdAt).toLocaleString()}</p>{q.response?<p className="mt-3 text-green-700">Your response: {q.response}</p>:<div className="mt-3"><textarea value={answers[q.id]??""} onChange={e=>setAnswers(x=>({...x,[q.id]:e.target.value}))} placeholder="Write your response…" className="border rounded p-2 w-full"/><button onClick={()=>void reply(q.id)} disabled={!answers[q.id]?.trim()} className="mt-2 bg-primary text-white rounded px-4 py-2 disabled:opacity-50">Send response</button></div>}</section>)}</div></>}</main>}
